### ISSUE TITLE
Error 'For Analytics object, you must specify a value to be set for setAffiliation' while creating CreditCard payment with Stripe

### ISSUE THREAD

**Issue by barryvdh** [elgentos/magento2-serversideanalytics#1]
When an order is created with Creditcard, this message occurs:
> For Analytics object, you must specify a value to be set for setAffiliation

I think that can only occur when `$order->getStoreName()` returns `null`. With iDeal this doesn't happen, but it does with CreditCard. Perhaps because the order is captured directly?

**Comment by peterjaap** [comment]
Thanks!!

**Comment by barryvdh** [comment]
Well the error is silenced, not sure if there's a problem when it's missing though
