### ISSUE TITLE
Client ID not correct

### ISSUE THREAD

**Issue by JoostWan** [elgentos/magento2-serversideanalytics#20]
The Client ID is retrieved from the Cookie `_ga`. 

The prefix is `GA1` but the part of the code does the checking for GA4 and UA1. So there is no match and the code returns null. Now the module created a random Client id and the data is Google Analytics is wrong because the conversion uses a different client id then the original from the visitor session. 

@indykoning maybe you can check this out, I saw the addition came from you 

```
if (
            $gaCookieVersion != 'GA' . $this->gaclient->getVersion() &&
            $gaCookieVersion != 'UA' . $this->uaclient->getVersion()
        ) {
            $this->logger->info('Google Analytics cookie version differs from Measurement Protocol API version; please upgrade.');
            return null;
        }

```

https://github.com/elgentos/magento2-serversideanalytics/blob/master/Observer/SaveGaUserId.php#L132

Some info; 

> Every Client ID has the structure: GA.1.1 + unique identifier + Unix timestamp. The Unix timestamp is the exact time and date the user 
first interacted with your pag

https://louder.com.au/2022/06/27/client-id-in-ga4-what-is-it-and-how-to-get-it-in-your-report/

We created a simple patch for testing with some clients and it's working.

```
@package elgentos/serversideanalytics2

diff --git a/Observer/SaveGaUserId.php b/Observer/SaveGaUserId.php
--- a/Observer/SaveGaUserId.php	
+++ b/Observer/SaveGaUserId.php	(date 1678796766430)
@@ -129,10 +129,7 @@
             return null;
         }
 
-        if (
-            $gaCookieVersion != 'GA' . $this->gaclient->getVersion() &&
-            $gaCookieVersion != 'UA' . $this->uaclient->getVersion()
-        ) {
+        if ($gaCookieVersion != 'GA' . $this->uaclient->getVersion()) {
             $this->logger->info('Google Analytics cookie version differs from Measurement Protocol API version; please upgrade.');
             return null;
         }
```

**Comment by mattiasghodsian** [comment]
Am getting `Google Analytics cookie version differs from Measurement Protocol API version` and checking the _ga cookies i see

![image](https://github.com/elgentos/magento2-serversideanalytics/assets/20265517/cfe7a4e3-667c-4aef-8089-9348caae1479)

**Comment by barryvdh** [comment]
My cookies are also in this format: `GA1.2.123456789.1234567890`
That means `$gaCookieVersion` = `GA1`. But the GA Clientversion is hardcoded to 4, so that will indeed never match.

That seems to be described here also:
https://www.optimizesmart.com/google-analytics-cookies-ultimate-guide/

<img width="651" alt="image" src="https://github.com/elgentos/magento2-serversideanalytics/assets/973269/8036c412-9f57-4e33-851c-1fab4ef286dc">

**Comment by JoostWan** [comment]
@barryvdh We created more changes for this module and testing it on some clients. You needed also the session_id otherwise the transactions can't related to a previous session in GA4.

**Comment by barryvdh** [comment]
PR in https://github.com/elgentos/magento2-serversideanalytics/pull/21
Can you try?

**Comment by barryvdh** [comment]
@JoostWan  Oh sorry, only see your message now. Can you create a (draft) pull request or send the diff/patch? Then I'll test as well.

**Comment by JoostWan** [comment]
@barryvdh I will create a pull request later this week. Need to remove the UA from the code also because it's not needed anymore.

**Comment by WouterSteen** [comment]
Yes, we Will try it also then! Nice work! Very much appreciated!!

**Comment by peterjaap** [comment]
I guess we can close this issue now, judging from #22.
